version: '3.4'

services:
  challengelgutierrez:
    image: challengelgutierrez
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
      - redis
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3030:4433 # 3001 EXPOSED PORT - 4433 SERVER RUNNING PORT

  db:
    container_name: mysql_db
    image: mysql:8.0
    env_file: .env
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: admin
      MYSQL_USER: test
      MYSQL_PASSWORD: test1234
    volumes:
      - ./db/config/mysql.ini:/etc/mysql/conf.d/my.ini # config file
      - ./db/config/db-dump:/docker-entrypoint-initdb.d
      - ./db/mysql-data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  redis:
    image: redis:6.2.6-alpine
    restart: always
    hostname: redis
    container_name: redis
    ports:
      - '6379:6379'
